---
- name: Restart gitlab
  ansible.builtin.command:
    cmd: docker restart "{{ gitlab__name }}"
  when: gitlab__container_state == 'started'
  ignore_errors: true
  register: gitlab_restart_result
  failed_when: false
  changed_when: gitlab_restart_result.rc == 0

# - name: reconfigure gitlab
#   community.docker.docker_container_exec:
#     container: "{{ gitlab__name }}"
#     command: gitlab-ctl reconfigure
#     chdir: /
