---
- name: Restart gitlab
  community.docker.docker_container:
    name: "{{ gitlab__name }}"
    restart: true

# - name: reconfigure gitlab
#   community.docker.docker_container_exec:
#     container: "{{ gitlab__name }}"
#     command: gitlab-ctl reconfigure
#     chdir: /
