---
- name: Converge GitLab CE Docker
  hosts: all
  become: true
  vars:
    gitlab__env:
      GITLAB_ROOT_PASSWORD: "molecule-test"
    gitlab__hostname: "gitlab.local"
    # Skip Docker service management in test environment
    docker_service_manage: false
    # Stabilize idempotence for directory ownership/mode in CI
    gitlab__directories:
      - path: "/opt/{{ gitlab__name }}"
        mode: "0760"
        owner: "root"
        group: "root"
      - path: "/opt/{{ gitlab__name }}/config"
        mode: "0770"
        owner: "root"
        group: "root"
      - path: "/opt/{{ gitlab__name }}/data"
        mode: "0770"
        owner: "root"
        group: "root"
      - path: "/opt/{{ gitlab__name }}/logs"
        mode: "0770"
        owner: "root"
        group: "root"
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: Wait for systemd to complete initialization (skipped in CI)
      ansible.builtin.command: systemctl is-system-running
      register: systemctl_status
      until: >
        'running' in systemctl_status.stdout or
        'degraded' in systemctl_status.stdout
      retries: 30
      delay: 5
      when: false  # skip in CI containers
      changed_when: false
      failed_when: systemctl_status.rc > 1

    - name: Check if Docker socket exists
      stat:
        path: /var/run/docker.sock
      register: docker_socket

    - name: Ensure Docker socket permissions are correct
      file:
        path: /var/run/docker.sock
        mode: '0666'
      when: docker_socket.stat.exists and docker_socket.stat.exists

  roles:
    - role: bsmeding.docker
      when: docker_socket.stat.exists and docker_socket.stat.exists
    - role: bsmeding.gitlab_docker
