---
- name: Verify - GitLab HTTP is running
  hosts: all
  become: false
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env','MOLECULE_PROJECT_DIRECTORY') }}/defaults"
        extensions: ["yml"]

    - name: Wait for GitLab HTTP port to be reachable
      ansible.builtin.wait_for:
        host: "localhost"
        port: "{{ gitlab__port_web_http }}"
        delay: 10         # Initial delay after container start
        timeout: 300      # Allow 5 minutes max for TCP port to open
        state: started

    - name: Wait until GitLab returns 200 OK
      ansible.builtin.uri:
        url: "http://localhost:{{ gitlab__port_web_http }}"
        return_content: true
      register: web_check
      retries: 15         # 15 x 20s = 5 minutes max
      delay: 20
      until: web_check.status == 200
      failed_when: web_check is failed or web_check.status != 200

    - name: Show result of HTTP check
      debug:
        var: web_check
