---
- name: Verify - Nginx is running
  hosts: all
  become: false
  tasks:
    - name: Get GitLab container IP
      command: docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' gitlab
      register: gitlab_ip
      changed_when: false

    - name: Debug container IP
      debug:
        var: gitlab_ip.stdout

    - name: Wait for GitLab port 80 to respond
      wait_for:
        host: "{{ gitlab_ip.stdout }}"
        port: 80
        timeout: 60

    - name: Test HTTP endpoint
      uri:
        url: "http://{{ gitlab_ip.stdout }}"
        status_code: 200
        return_content: true
      register: result

    - name: Debug result
      debug:
        var: result
