- name: Verify - GitLab HTTP is running
  hosts: all
  become: false
  tasks:
    - name: Include default vars
      ansible.builtin.include_vars:
        dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/defaults/"
        extensions: ["yml"]

    - name: Wait for GitLab mapped port on host to become reachable
      wait_for:
        host: "127.0.0.1"
        port: "{{ gitlab__port_web_http }}"
        timeout: 600

    - name: Wait until GitLab returns 200 OK
      ansible.builtin.uri:
        url: "http://127.0.0.1:{{ gitlab__port_web_http }}"
        return_content: true
      register: web_check
      retries: 30         # Up to 10 minutes (30 × 20s)
      delay: 20
      until: web_check.status == 200
      failed_when: web_check is failed or web_check.status != 200

    - name: Debug response content
      debug:
        var: web_check.content
