---
- name: Converge
  hosts: all
  become: false
  roles:
    - role: bsmeding.gitlab_docker
  vars:
    gitlab__env:
      GITLAB_ROOT_PASSWORD: "molecule-test"
    gitlab__hostname: "gitlab.local"
